### ISSUE TITLE
[Feature Request] Show last synced time at MLS BD leaderboard

### ISSUE THREAD

**Issue by bellayet** [mozillabd/homepage#10]
When people visit the MLS BD leaderboard often complain that the BD leaderboard doesn't showing same points or place as original leaderboard. The answer is you are watching the data, till last synced or updated not live. So I think it would be a good idea if we can show anywhere (I prefer at the bottom) in the page, what is the last synced time for the score.

Could you please include and show the last synced date and time at the page. So that people can get the idea what they are watching?

@anistuhin

**Comment by anistuhin** [comment]
That's a very good one, Bellayet vai. I'm on it.

**Comment by anistuhin** [comment]
Currently not applicable as it shows live data.
