### ISSUE TITLE
Realtime update on MLS leaderboard

### ISSUE THREAD

**Issue by seeam** [mozillabd/homepage#7]
Current MLS leaderboard for Bangladeshi contributors doesn't show real time updates.

**Comment by anistuhin** [comment]
As we are scraping data from the main leaderboard, showing real time data needs us to run the scrapers every time an user hits. And as we are scraping from two different urls this needs some processing time which will make the site slow showing data. So, to make the page faster and reducing server request to main leaderboard we are showing data which are updated hourly. So, the data gets updated every hour. Let me know if anything else :)

**Comment by anistuhin** [comment]
Closing this issue.
